apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todoui-nuxt
  name: todoui-nuxt
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: todoui-nuxt
  type: LoadBalancer
status:
  loadBalancer: {}