apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgresdb
  name: postgresdb
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresdb
status:
  loadBalancer: {}