apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgresdb
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresdb
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: matthias
        - name: POSTGRES_DB
          value: mydb
        resources: {}
status: {}